version: '3'

services:
  app:
    build: .
    entrypoint: npm run start  
    volumes:
      - .:/home/node/app
    networks:
      - app-networks
    ports:
      - "3000:3000"
    depends_on:
      - db    
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nest
    ports:
      - "3306:3306"
    networks:
      - app-networks    
networks:
  app-networks:
    driver: bridge